# permissions for end users to view workerdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workerdefinition-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workerdefinition
    app.kubernetes.io/part-of: workerdefinition
    app.kubernetes.io/managed-by: kustomize
  name: workerdefinition-viewer-role
rules:
- apiGroups:
  - api.worker-definition
  resources:
  - workerdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.worker-definition
  resources:
  - workerdefinitions/status
  verbs:
  - get
